# Generated by Django 3.1.2 on 2021-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20210706_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(default=None, upload_to='objects'),
        ),
    ]
