# Generated by Django 3.1.2 on 2021-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_object_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
